name: Deploy Prod Lambda
on:
  push:
    branches: [ prod ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Preload Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Build and Push
        shell: bash
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          IAM_ROLE_ARN: ${{ secrets.LAMBDA_ARN }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME_PROD }}
          STAGE: prod_v1
        run: |
          pip install -r requirements.txt
          # Make .env file
          echo "MONGO_URI=$MONGO_URI" >> .env
          echo "IAM_ROLE_ARN=$IAM_ROLE_ARN" >> .env
          echo "DOMAIN_NAME=$DOMAIN_NAME" >> .env
          echo "CERTIFICATE_ARN=${{ secrets.CERTIFICATE_ARN }}" >> .env
          echo "DB_QUEUE_NAME=${{ secrets.DB_SQS_NAME_PROD }}" >> .env
          echo "SEARCH_ENGINE_URI=${{ secrets.SEARCH_ENGINE_URI_PROD }}" >> .env

          python -m pytest -v
          python deploy.py --stage=${{ env.STAGE }}

      - name: Deploy Alarm
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: C05NYKY1KS6
          author_name: Github Action
          fields: repo,commit,message,author,took,workflow
          mention: here
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
